package regex_matching;//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int BAR = 10;
  public static final int DASH = 2;
  public static final int STAR = 8;
  public static final int PLUS = 9;
  public static final int EOF = 0;
  public static final int RIGHT_BRACKET = 6;
  public static final int error = 1;
  public static final int LEFT_BRACKET = 5;
  public static final int LEFT_SQUARE_BRACKET = 3;
  public static final int RIGHT_SQUARE_BRACKET = 4;
  public static final int CHAR = 11;
  public static final int QUESTION_MARK = 7;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "DASH",
  "LEFT_SQUARE_BRACKET",
  "RIGHT_SQUARE_BRACKET",
  "LEFT_BRACKET",
  "RIGHT_BRACKET",
  "QUESTION_MARK",
  "STAR",
  "PLUS",
  "BAR",
  "CHAR"
  };
}

